Reformat changelog
This makes it palatable to automatic releases with
https://github.com/marketplace/actions/git-release

Done with:

    sed -i '/^0/ { s/^/## [/; s/ (/] - /; s/)$// }; /^----/d' NEWS

diff --git a/do-release b/do-release
--- a/do-release
+++ b/do-release
@@ -13,12 +13,12 @@ set -e
 git clean -fdx
 
 # update version in NEWS
-version=$(grep '(UNRELEASED)' NEWS | cut -f1 -d' ')
+version=$(sed -rn '1 { s/^.*\[([0-9.]+)\].*/\1/; p }' NEWS)
 [ -n "$version" ] || {
-    echo "no UNRELEASED in NEWS" >&2
+    echo "failed to parse version" >&2
     exit 1
 }
-sed -i "s/(UNRELEASED)/$(date '+(%Y-%m-%d)')/" NEWS
+sed -i "s/UNRELEASED/$(date '+%Y-%m-%d')/" NEWS
 
 # update version in package
 sed -i -r "s/__version__ = '[0-9.]*'/__version__ = '${version}'/" dbusmock/__init__.py
@@ -26,7 +26,7 @@ sed -i -r "s/__version__ = '[0-9.]*'/__version__ = '${version}'/" dbusmock/__ini
 # commit release and tag
 git add NEWS dbusmock/__init__.py
 git commit -m "release $version"
-changes=$(grep --max-count=1 -A1000 '^------' NEWS | grep -v '^--------' | grep -B1000  --max-count=1 '^$')
+changes=$(sed -n '/^$/ q; /^- / p' NEWS)
 printf "$version\n\n$changes\n" | git tag -s -F- $version
 
 git push
